backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: beverage
    label: Beverage
    folder: beverage
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: desc, label: Desc, widget: markdown }
      - { label: "Small Price", name: sprice, widget: number }
      - { label: "Regular Price", name: rprice, widget: number }